FROM debian:jessie

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get -y upgrade && apt-get install -y locales supervisor
RUN apt-get install -y php5-mysql php5-xmlrpc php5-readline php5-ldap php5-json \
php5-curl php5-cli php5-mcrypt php5-fpm nano curl apt-transport-https gnupg2 \
php5-odbc libmdbodbc1 unixodbc libmyodbc odbc-postgresql

RUN apt-get install -y apache2 libapache2-mod-php5 php5-xdebug

RUN apt-get install -y php5-mysql

COPY apache-default.conf /etc/apache2/sites-available/000-default.conf

RUN a2enmod rewrite
COPY cmd.sh /bin/

RUN chmod +x /bin/cmd.sh
RUN ln -s /usr/lib/x86_64-linux-gnu/libodbccr.so.2 /usr/lib/x86_64-linux-gnu/libodbccr.so