version: '3'
services:
    atsistemas-web:
        image: atsistemas:web
        hostname: at.web.local
        privileged: true
        ports:
            - "80:80"
        volumes:
            - E:/Desarrollo/old-php-docker/source/web:/var/www/html/public
            - E:/Desarrollo/old-php-docker/profiler/web:/var/www/profiler
            - E:/Desarrollo/old-php-docker/client-log:/var/log/apache2
        links:
            - atsistemas-databases
            - atsistemas-api
    atsistemas-api:
        image: atsistemas:api
        hostname: at.api.local
        privileged: true
        ports:
            - "8080:80"
        volumes:
            - E:/Desarrollo/old-php-docker/source/api:/var/www/html
            - E:/Desarrollo/old-php-docker/profiler/api:/var/www/profiler
            - E:/Desarrollo/old-php-docker/api-log:/var/log/apache2
        environment:
            TZ: "Europe/Madrid"
            DB_CONNECTION: mysql
            DB_HOST: atsistemas-databases
            DB_PORT: 3306
            DB_DATABASE: atsistemas
            DB_USERNAME: atUser
            DB_PASSWORD: atPassword
        links:
            - atsistemas-databases
    atsistemas-databases:
        image: mysql:5.7
        restart: always
        ports:
            - "33306:3306"
        volumes:
            - E:/Desarrollo/old-php-docker/data:/var/lib/mysql
        environment:
            TZ: "Europe/Madrid"
            MYSQL_HOST: "localhost"
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_USER: 'atUser'
            MYSQL_PASSWORD: 'atPassword'
            MYSQL_DATABASE: 'at_db'
        command: --max_allowed_packet=1024M